"""initial schema

Revision ID: e4f9057b5a5b
Revises: 
Create Date: 2025-11-27 23:41:27.986598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f9057b5a5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runbooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('markdown', sa.Text(), nullable=True),
    sa.Column('json_blob', sa.Text(), nullable=True),
    sa.Column('tickets_used', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runbooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runbooks_topic'), ['topic'], unique=False)

    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('work_notes', sa.Text(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('subcategory', sa.String(length=128), nullable=True),
    sa.Column('assignment_group', sa.String(length=128), nullable=True),
    sa.Column('ci', sa.String(length=256), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('topic', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tickets_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_topic'), ['topic'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_topic'))
        batch_op.drop_index(batch_op.f('ix_tickets_number'))

    op.drop_table('tickets')
    with op.batch_alter_table('runbooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runbooks_topic'))

    op.drop_table('runbooks')
    # ### end Alembic commands ###
